// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyVatTu_ASP.DataAccess;

#nullable disable

namespace QuanLyVatTu_ASP.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260225150507_AddPointAndTier")]
    partial class AddPointAndTier
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.ChiTietDonHang", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaDonHang")
                        .HasColumnType("int");

                    b.Property<int>("MaVatTu")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal?>("SoTienDatCoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ThanhTien")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18,2)")
                        .HasComputedColumnSql("[SoLuong] * [DonGia]", true);

                    b.HasKey("ID");

                    b.HasIndex("MaDonHang");

                    b.HasIndex("MaVatTu");

                    b.ToTable("ChiTietDonHang", (string)null);
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.ChiTietGioHang", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("MaGioHang")
                        .HasColumnType("int");

                    b.Property<int>("MaVatTu")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MaGioHang");

                    b.HasIndex("MaVatTu");

                    b.ToTable("ChiTietGioHang");
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.ChiTietHoaDon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal?>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaHoaDon")
                        .HasColumnType("int");

                    b.Property<int>("MaVatTu")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<decimal>("ThanhTien")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18,2)")
                        .HasComputedColumnSql("[SoLuong] * [DonGia]", true);

                    b.HasKey("ID");

                    b.HasIndex("MaHoaDon");

                    b.HasIndex("MaVatTu");

                    b.ToTable("ChiTietHoaDon", (string)null);
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.ChiTietYeuCauBaoGia", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal?>("DonGiaDuKien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int>("VatTuId")
                        .HasColumnType("int")
                        .HasColumnName("MaVatTu");

                    b.Property<int>("YeuCauBaoGiaId")
                        .HasColumnType("int")
                        .HasColumnName("MaYeuCau");

                    b.HasKey("ID");

                    b.HasIndex("VatTuId");

                    b.HasIndex("YeuCauBaoGiaId");

                    b.ToTable("ChiTietYeuCauBaoGia", (string)null);
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.DanhGia", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BinhLuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChatLuongSanPham")
                        .HasColumnType("int");

                    b.Property<int>("LuotThich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<int>("MaVatTu")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("NgayPhanHoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhanHoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoSao")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaVatTu");

                    b.ToTable("DanhGia", (string)null);
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.DonHang", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("KhachHangId")
                        .HasColumnType("int")
                        .HasColumnName("MaKhachHang");

                    b.Property<string>("MaHienThi")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("varchar(20)")
                        .HasComputedColumnSql("'DH' + CONVERT(VARCHAR(4), YEAR([NgayDat])) + '-' + RIGHT('000' + CAST([ID] AS VARCHAR(3)), 3)");

                    b.Property<DateTime>("NgayDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("NgayDatCoc")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("NhanVienId")
                        .HasColumnType("int")
                        .HasColumnName("MaNhanVien");

                    b.Property<string>("PhuongThucDatCoc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("SoTienDatCoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TongTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Chờ xác nhận");

                    b.HasKey("ID");

                    b.HasIndex("KhachHangId");

                    b.HasIndex("NhanVienId");

                    b.ToTable("DonHang", (string)null);
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.GioHang", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MaKhachHang");

                    b.ToTable("GioHang");
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.HangThanhVien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("ChiTieuToiThieu")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ChiTieuToiThieu");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("PhanTramChietKhau")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("PhanTramChietKhau");

                    b.Property<string>("TenHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenHang");

                    b.HasKey("ID");

                    b.HasIndex("TenHang")
                        .IsUnique();

                    b.ToTable("HangThanhVien", null, t =>
                        {
                            t.HasCheckConstraint("CK_HangThanhVien_ChiTieuToiThieu", "[ChiTieuToiThieu] >= 0");

                            t.HasCheckConstraint("CK_HangThanhVien_PhanTramChietKhau", "[PhanTramChietKhau] >= 0 AND [PhanTramChietKhau] <= 100");
                        });
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.HoaDon", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal?>("ChietKhau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("DiaChiDKKD")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DiaChiNguoiBan")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EmailNhanHoaDon")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GhiChuVAT")
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsVATInvoice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("MaDonHang")
                        .HasColumnType("int");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<string>("MaSoThue")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaSoThueBan")
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayLap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayLap")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("PhuongThucThanhToan")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SoHoaDonVAT")
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("SoTienDatCoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("TenCongTy")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenNguoiBan")
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("ThueSuat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(10m);

                    b.Property<decimal?>("TienThueGTGT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TongTienSauThue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TongTienTruocThue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Đã thanh toán");

                    b.Property<decimal>("TyLeThueGTGT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(10m);

                    b.HasKey("ID");

                    b.HasIndex("MaDonHang");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaNhanVien");

                    b.ToTable("HoaDon", null, t =>
                        {
                            t.HasCheckConstraint("CK_HoaDon_ChietKhau", "[ChietKhau] >= 0");

                            t.HasCheckConstraint("CK_HoaDon_SoTienDatCoc", "[SoTienDatCoc] >= 0");

                            t.HasCheckConstraint("CK_HoaDon_TongTienTruocThue", "[TongTienTruocThue] > 0");

                            t.HasCheckConstraint("CK_HoaDon_TyLeThueGTGT", "[TyLeThueGTGT] IN (0, 10)");
                        });
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.KhachHang", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("DangNhapGoogle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("DiemTichLuy")
                        .HasColumnType("int")
                        .HasColumnName("DiemTichLuy");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaHangThanhVien")
                        .HasColumnType("int")
                        .HasColumnName("MaHangThanhVien");

                    b.Property<string>("MaHienThi")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("varchar(20)")
                        .HasComputedColumnSql("'KH' + RIGHT('000' + CAST([ID] AS VARCHAR(3)), 3)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("NgayHetHanHang")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayHetHanHang");

                    b.Property<DateTime?>("NgayLenHang")
                        .HasColumnType("datetime")
                        .HasColumnName("NgayLenHang");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("TaiKhoan")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MaHangThanhVien");

                    b.HasIndex("TaiKhoan")
                        .IsUnique();

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.LichSuSuDungVoucher", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("MaDonHang")
                        .HasColumnType("int")
                        .HasColumnName("MaDonHang");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int")
                        .HasColumnName("MaKhachHang");

                    b.Property<int>("MaVoucherGoc")
                        .HasColumnType("int")
                        .HasColumnName("MaVoucherGoc");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("SoTienGiamSnapshot")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SoTienGiamSnapshot");

                    b.Property<string>("TenKhachHangSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TenKhachHangSnapshot");

                    b.Property<DateTime>("ThoiGianSuDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ThoiGianSuDung")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("TrangThaiSuDung")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("TrangThaiSuDung");

                    b.HasKey("ID");

                    b.HasIndex("MaDonHang")
                        .HasDatabaseName("IX_LichSuSuDung_DonHang");

                    b.HasIndex("MaVoucherGoc");

                    b.HasIndex("MaDonHang", "MaVoucherGoc")
                        .IsUnique()
                        .HasDatabaseName("IX_LichSuSuDung_DonHang_Voucher_Unique");

                    b.HasIndex("MaKhachHang", "MaVoucherGoc")
                        .HasDatabaseName("IX_LichSuSuDung_KhachHang_Voucher");

                    b.ToTable("LichSuSuDungVoucher", null, t =>
                        {
                            t.HasCheckConstraint("CK_LichSuSuDungVoucher_SoTienGiam", "[SoTienGiamSnapshot] >= 0");

                            t.HasCheckConstraint("CK_LichSuSuDungVoucher_TrangThai", "[TrangThaiSuDung] IN ('APPLIED', 'REFUNDED', 'BURNED')");
                        });
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.LichSuTichDiem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("LoaiGiaoDich")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("LoaiGiaoDich");

                    b.Property<int>("MaDonHang")
                        .HasColumnType("int")
                        .HasColumnName("MaDonHang");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int")
                        .HasColumnName("MaKhachHang");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("SoDiem")
                        .HasColumnType("int")
                        .HasColumnName("SoDiem");

                    b.HasKey("ID");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaDonHang", "LoaiGiaoDich")
                        .IsUnique()
                        .HasDatabaseName("IX_LichSuTichDiem_DonHang_LoaiGiaoDich_Unique");

                    b.ToTable("LichSuTichDiem", null, t =>
                        {
                            t.HasCheckConstraint("CK_LichSuTichDiem_LoaiGiaoDich", "[LoaiGiaoDich] IN ('EARN', 'REDEEM', 'REFUND', 'CLAWBACK')");
                        });
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.LoaiVatTu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("MaHienThi")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("varchar(20)")
                        .HasComputedColumnSql("'LVT' + RIGHT('000' + CAST([ID] AS VARCHAR(3)), 3)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("TenLoaiVatTu")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("LoaiVatTu", (string)null);
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.NhaCungCap", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MaHienThi")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("varchar(20)")
                        .HasComputedColumnSql("'NCC' + RIGHT('000' + CAST([ID] AS VARCHAR(3)), 3)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("TenNhaCungCap")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("NhaCungCap", (string)null);
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.NhanVien", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasColumnType("varchar(12)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaHienThi")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("varchar(20)")
                        .HasComputedColumnSql("'NV' + RIGHT('000' + CAST([ID] AS VARCHAR(3)), 3)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("TaiKhoan")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("TaiKhoan")
                        .IsUnique();

                    b.HasIndex("NgaySinh", "CCCD", "SoDienThoai")
                        .IsUnique();

                    b.ToTable("NhanVien", (string)null);
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.TuongTacDanhGia", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("DaThich")
                        .HasColumnType("bit");

                    b.Property<int>("MaDanhGia")
                        .HasColumnType("int");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTuongTac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("ID");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaDanhGia", "MaKhachHang")
                        .IsUnique();

                    b.ToTable("TuongTacDanhGia", (string)null);
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.VatTu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GiaNhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaHienThi")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("varchar(20)")
                        .HasComputedColumnSql("'VT' + RIGHT('000' + CAST([ID] AS VARCHAR(3)), 3)");

                    b.Property<int>("MaLoaiVatTu")
                        .HasColumnType("int");

                    b.Property<int>("MaNhaCungCap")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("SoLuongTon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TenVatTu")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("MaLoaiVatTu");

                    b.HasIndex("MaNhaCungCap");

                    b.ToTable("VatTu", null, t =>
                        {
                            t.HasCheckConstraint("CK_VatTu_GiaBan", "[GiaBan] >= 0");

                            t.HasCheckConstraint("CK_VatTu_GiaNhap", "[GiaNhap] >= 0");

                            t.HasCheckConstraint("CK_VatTu_SoLuongTon", "[SoLuongTon] >= 0");
                        });
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.ViVoucherKhachHang", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int")
                        .HasColumnName("MaKhachHang");

                    b.Property<int>("MaVoucherGoc")
                        .HasColumnType("int")
                        .HasColumnName("MaVoucherGoc");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("ThoiGianLuuMa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ThoiGianLuuMa")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("TrangThaiTrongVi")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("TrangThaiTrongVi");

                    b.HasKey("ID");

                    b.HasIndex("MaVoucherGoc");

                    b.HasIndex("MaKhachHang", "MaVoucherGoc")
                        .IsUnique()
                        .HasDatabaseName("IX_ViVoucher_KhachHang_Voucher_Unique");

                    b.ToTable("ViVoucherKhachHang", null, t =>
                        {
                            t.HasCheckConstraint("CK_ViVoucherKhachHang_TrangThai", "[TrangThaiTrongVi] IN ('AVAILABLE', 'USED', 'EXPIRED')");
                        });
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.Voucher", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("GiaTriDonHangToiThieu")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("GiaTriDonHangToiThieu");

                    b.Property<decimal>("GiaTriGiam")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("GiaTriGiam");

                    b.Property<int>("GioiHanSuDungMoiUser")
                        .HasColumnType("int")
                        .HasColumnName("GioiHanSuDungMoiUser");

                    b.Property<string>("LoaiGiamGia")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("LoaiGiamGia");

                    b.Property<int?>("MaNhanVienTao")
                        .HasColumnType("int")
                        .HasColumnName("MaNhanVienTao");

                    b.Property<string>("MaVoucher")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("MaVoucher");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("SoLuongDaDung")
                        .HasColumnType("int")
                        .HasColumnName("SoLuongDaDung");

                    b.Property<decimal?>("SoTienGiamToiDa")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SoTienGiamToiDa");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime")
                        .HasColumnName("ThoiGianBatDau");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("datetime")
                        .HasColumnName("ThoiGianKetThuc");

                    b.Property<int>("TongSoLuong")
                        .HasColumnType("int")
                        .HasColumnName("TongSoLuong");

                    b.Property<string>("TrangThaiGoc")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("TrangThaiGoc");

                    b.HasKey("ID");

                    b.HasIndex("MaNhanVienTao");

                    b.HasIndex("MaVoucher")
                        .IsUnique();

                    b.ToTable("Voucher", null, t =>
                        {
                            t.HasCheckConstraint("CK_Voucher_GiaTriDonHangToiThieu", "[GiaTriDonHangToiThieu] >= 0");

                            t.HasCheckConstraint("CK_Voucher_GiaTriGiam", "([LoaiGiamGia] = 'FIXED' AND [GiaTriGiam] > 0) OR ([LoaiGiamGia] = 'PERCENT' AND [GiaTriGiam] > 0 AND [GiaTriGiam] <= 100)");

                            t.HasCheckConstraint("CK_Voucher_GioiHanSuDung", "[GioiHanSuDungMoiUser] >= 1");

                            t.HasCheckConstraint("CK_Voucher_LoaiGiamGia", "[LoaiGiamGia] IN ('PERCENT', 'FIXED')");

                            t.HasCheckConstraint("CK_Voucher_SoLuongDaDung", "[SoLuongDaDung] >= 0");

                            t.HasCheckConstraint("CK_Voucher_SoLuong_HopLe", "[SoLuongDaDung] <= [TongSoLuong]");

                            t.HasCheckConstraint("CK_Voucher_ThoiGian_HopLe", "[ThoiGianBatDau] < [ThoiGianKetThuc]");

                            t.HasCheckConstraint("CK_Voucher_TongSoLuong", "[TongSoLuong] >= 0");

                            t.HasCheckConstraint("CK_Voucher_TrangThaiGoc", "[TrangThaiGoc] IN ('ACTIVE', 'EXPIRED', 'REVOKED')");
                        });
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.YeuCauBaoGia", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("KhachHangId")
                        .HasColumnType("int")
                        .HasColumnName("MaKhachHang");

                    b.Property<string>("MaHienThi")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("NgayHetHan")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal?>("TongTienDuKien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.HasIndex("KhachHangId");

                    b.ToTable("YeuCauBaoGia", (string)null);
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.YeuThich", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<int>("MaVatTu")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("ID");

                    b.HasIndex("MaVatTu");

                    b.HasIndex("MaKhachHang", "MaVatTu")
                        .IsUnique();

                    b.ToTable("YeuThich", (string)null);
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Models.DiaChiNhanHang", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("KhachHangId")
                        .HasColumnType("int");

                    b.Property<double?>("KinhDo")
                        .HasColumnType("float");

                    b.Property<string>("LoaiDiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("MacDinh")
                        .HasColumnType("bit");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<double?>("ViDo")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("KhachHangId");

                    b.ToTable("DiaChiNhanHang");
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("QuanLyVatTu_ASP.Areas.Admin.Models.DonHang", "DonHang")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaDonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyVatTu_ASP.Areas.Admin.Models.VatTu", "VatTu")
                        .WithMany()
                        .HasForeignKey("MaVatTu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("VatTu");
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.ChiTietGioHang", b =>
                {
                    b.HasOne("QuanLyVatTu_ASP.Areas.Admin.Models.GioHang", "GioHang")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("MaGioHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyVatTu_ASP.Areas.Admin.Models.VatTu", "VatTu")
                        .WithMany()
                        .HasForeignKey("MaVatTu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GioHang");

                    b.Navigation("VatTu");
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.ChiTietHoaDon", b =>
                {
                    b.HasOne("QuanLyVatTu_ASP.Areas.Admin.Models.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyVatTu_ASP.Areas.Admin.Models.VatTu", "VatTu")
                        .WithMany()
                        .HasForeignKey("MaVatTu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("VatTu");
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.ChiTietYeuCauBaoGia", b =>
                {
                    b.HasOne("QuanLyVatTu_ASP.Areas.Admin.Models.VatTu", "VatTu")
                        .WithMany()
                        .HasForeignKey("VatTuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyVatTu_ASP.Areas.Admin.Models.YeuCauBaoGia", "YeuCauBaoGia")
                        .WithMany("ChiTietYeuCauBaoGias")
                        .HasForeignKey("YeuCauBaoGiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VatTu");

                    b.Navigation("YeuCauBaoGia");
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.DanhGia", b =>
                {
                    b.HasOne("QuanLyVatTu_ASP.Areas.Admin.Models.KhachHang", "KhachHang")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyVatTu_ASP.Areas.Admin.Models.VatTu", "VatTu")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaVatTu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("VatTu");
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.DonHang", b =>
                {
                    b.HasOne("QuanLyVatTu_ASP.Areas.Admin.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyVatTu_ASP.Areas.Admin.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.GioHang", b =>
                {
                    b.HasOne("QuanLyVatTu_ASP.Areas.Admin.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.HoaDon", b =>
                {
                    b.HasOne("QuanLyVatTu_ASP.Areas.Admin.Models.DonHang", "DonHang")
                        .WithMany()
                        .HasForeignKey("MaDonHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyVatTu_ASP.Areas.Admin.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyVatTu_ASP.Areas.Admin.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.KhachHang", b =>
                {
                    b.HasOne("QuanLyVatTu_ASP.Areas.Admin.Models.HangThanhVien", "HangThanhVien")
                        .WithMany("KhachHangs")
                        .HasForeignKey("MaHangThanhVien")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HangThanhVien");
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.LichSuSuDungVoucher", b =>
                {
                    b.HasOne("QuanLyVatTu_ASP.Areas.Admin.Models.DonHang", "DonHang")
                        .WithMany("LichSuSuDungVouchers")
                        .HasForeignKey("MaDonHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyVatTu_ASP.Areas.Admin.Models.KhachHang", "KhachHang")
                        .WithMany("LichSuSuDungVouchers")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyVatTu_ASP.Areas.Admin.Models.Voucher", "VoucherGoc")
                        .WithMany("LichSuSuDungVouchers")
                        .HasForeignKey("MaVoucherGoc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("KhachHang");

                    b.Navigation("VoucherGoc");
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.LichSuTichDiem", b =>
                {
                    b.HasOne("QuanLyVatTu_ASP.Areas.Admin.Models.DonHang", "DonHang")
                        .WithMany("LichSuTichDiems")
                        .HasForeignKey("MaDonHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyVatTu_ASP.Areas.Admin.Models.KhachHang", "KhachHang")
                        .WithMany("LichSuTichDiems")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.TuongTacDanhGia", b =>
                {
                    b.HasOne("QuanLyVatTu_ASP.Areas.Admin.Models.DanhGia", "DanhGia")
                        .WithMany("TuongTacDanhGias")
                        .HasForeignKey("MaDanhGia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyVatTu_ASP.Areas.Admin.Models.KhachHang", "KhachHang")
                        .WithMany("TuongTacDanhGias")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DanhGia");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.VatTu", b =>
                {
                    b.HasOne("QuanLyVatTu_ASP.Areas.Admin.Models.LoaiVatTu", "LoaiVatTu")
                        .WithMany("VatTus")
                        .HasForeignKey("MaLoaiVatTu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyVatTu_ASP.Areas.Admin.Models.NhaCungCap", "NhaCungCap")
                        .WithMany("VatTus")
                        .HasForeignKey("MaNhaCungCap")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoaiVatTu");

                    b.Navigation("NhaCungCap");
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.ViVoucherKhachHang", b =>
                {
                    b.HasOne("QuanLyVatTu_ASP.Areas.Admin.Models.KhachHang", "KhachHang")
                        .WithMany("ViVoucherKhachHangs")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyVatTu_ASP.Areas.Admin.Models.Voucher", "VoucherGoc")
                        .WithMany("ViVoucherKhachHangs")
                        .HasForeignKey("MaVoucherGoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("VoucherGoc");
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.Voucher", b =>
                {
                    b.HasOne("QuanLyVatTu_ASP.Areas.Admin.Models.NhanVien", "NhanVienTao")
                        .WithMany()
                        .HasForeignKey("MaNhanVienTao")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NhanVienTao");
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.YeuCauBaoGia", b =>
                {
                    b.HasOne("QuanLyVatTu_ASP.Areas.Admin.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.YeuThich", b =>
                {
                    b.HasOne("QuanLyVatTu_ASP.Areas.Admin.Models.KhachHang", "KhachHang")
                        .WithMany("YeuThichs")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyVatTu_ASP.Areas.Admin.Models.VatTu", "VatTu")
                        .WithMany("YeuThichs")
                        .HasForeignKey("MaVatTu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("VatTu");
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Models.DiaChiNhanHang", b =>
                {
                    b.HasOne("QuanLyVatTu_ASP.Areas.Admin.Models.KhachHang", "KhachHang")
                        .WithMany("DiaChiNhanHangs")
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.DanhGia", b =>
                {
                    b.Navigation("TuongTacDanhGias");
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("LichSuSuDungVouchers");

                    b.Navigation("LichSuTichDiems");
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.GioHang", b =>
                {
                    b.Navigation("ChiTietGioHangs");
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.HangThanhVien", b =>
                {
                    b.Navigation("KhachHangs");
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.KhachHang", b =>
                {
                    b.Navigation("DanhGias");

                    b.Navigation("DiaChiNhanHangs");

                    b.Navigation("LichSuSuDungVouchers");

                    b.Navigation("LichSuTichDiems");

                    b.Navigation("TuongTacDanhGias");

                    b.Navigation("ViVoucherKhachHangs");

                    b.Navigation("YeuThichs");
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.LoaiVatTu", b =>
                {
                    b.Navigation("VatTus");
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.NhaCungCap", b =>
                {
                    b.Navigation("VatTus");
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.VatTu", b =>
                {
                    b.Navigation("DanhGias");

                    b.Navigation("YeuThichs");
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.Voucher", b =>
                {
                    b.Navigation("LichSuSuDungVouchers");

                    b.Navigation("ViVoucherKhachHangs");
                });

            modelBuilder.Entity("QuanLyVatTu_ASP.Areas.Admin.Models.YeuCauBaoGia", b =>
                {
                    b.Navigation("ChiTietYeuCauBaoGias");
                });
#pragma warning restore 612, 618
        }
    }
}
